### ISSUE TITLE
KeyError thrown for some items 

### ISSUE THREAD

**Issue by dibyaaaaax** [mediawiki-utilities/python-mwbase#8]
Here is a list of items that throws an error.
Q140
Q275937
Q310332
Q312656
Q328627
Q330336
Q600393

**Traceback**
```
>>> wb_doc = requests.get("https://wikidata.org/wiki/Special:EntityData/Q312656.json").json()
>>> entity = mwbase.Entity.from_json(wb_doc['entities']['Q312656'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/entity.py", line 9, in from_json
    return normalize(entity_doc)
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/entity.py", line 31, in normalize
    in (entity_doc.get('claims', {}) or {}).items()}),
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/entity.py", line 30, in <dictcomp>
    for pid, claim_docs
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/entity.py", line 29, in <listcomp>
    for claim_doc in claim_docs]
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/statement.py", line 30, in normalize
    for prop in statement_doc.get('qualifiers-order', [])}
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/statement.py", line 30, in <dictcomp>
    for prop in statement_doc.get('qualifiers-order', [])}
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/statement.py", line 29, in <listcomp>
    for qualifier_doc in statement_doc['qualifiers'][prop]]
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/claim.py", line 16, in normalize
    'datavalue': datavalue.normalize(claim_doc.get('datavalue')),
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/datavalue.py", line 21, in normalize
    return normalize_entityid(datavalue_doc)
  File "/home/dibya/.local/lib/python3.6/site-packages/mwbase/datavalue.py", line 119, in normalize_entityid
    'numeric-id': datavalue_doc['value']['numeric-id'],
KeyError: 'numeric-id'
```

**Comment by halfak** [comment]
Looks like this is due to changes for lexemes.  Here's the offending datavalue from Q140:
```
{'value': {'entity-type': 'sense', 'id': 'L17815-S1'}, 'type': 'wikibase-entityid'}
```
Here we have a wikibase-entityid without a corresponding numeric-id.  We can fix this by making the numeric-id None when it doesn't exist in the wikidata item.
